### ISSUE TITLE
Big Lag if enemy is inside of the BulletSpawn of BlastPulse

### ISSUE THREAD

**Issue by HurricanKai** [Jeremi247/TopDown#3]
So:

There is an Extreme Lag, if there is an Enemy where all of the Bullets Spawn. (i found that out while playing with the Position of the Spawn)

I think it Occures Somehow like this:

The Dection get that there is an Collision,
It delets and Spawns the *PARTICLES*
but befor it deletes the enemy, it already detects that for the next bullet.
the Result is that there is an massive amount of particles which Monogame with your game "engine" does not like...

**Comment by HurricanKai** [comment]
Fixed:
in Fade:
```
			if (Actors.BloodParticles.Count > 100 || Actors.DeadBodies.Count > 100)
			{
				ShouldBeRemoved = true;
			}
```

**Comment by Jeremi247** [comment]
Actually it could be checked in the collision detection if the enemy function ShouldBeRemoved returns true, if yes then should ignore collision with bullet. Thus there won't be more collisions than one with enemy and only one spawnPartciles event will be fired

**Comment by HurricanKai** [comment]
Yes, Thanks :)
Nice fix there!
